model:
  name: mobilenetv2
  width_multipler: 1.0

num_epochs: 150
batch_size: 512

criterion:
  name: xent

optimizer:
  name: sgd
  lr: 0.05
  momentum: 0.9
  weight_decay: 4.0e-5

scheduler:
  name: cosine